<?php

return [

    'serverId' => [
        'anton' => '안톤',
        'bakal' => '바칼',
        'cain' => '카인',
        'casillas' => '카시야스',
        'diregie' => '디레지에',
        'hilder' => '힐더',
        'prey' => '프레이',
        'siroco' => '시로코',
    ],

    'rarity' => [
        '커먼' => '#FFFFFF',
        '언커먼' => '#68D5ED',
        '레어' => '#B36BFF',
        '유니크' => '#FF00FF',
        '에픽' => '#FFB400',
        '크로니클' => '#FF6666',
        '레전더리' => '#FF7800',
    ],

    'code' => [
        '101' => '캐릭터 생성',
        '102' => '캐릭터명 변경',
        '103' => '캐릭터 전직',
        '104' => '캐릭터 최고 레벨 달성',
        '201' => '레이드',
        '202' => '비전의 탑 정복',
        '203' => '절망의 탑 정복',
        '204' => '마수던전 토벌',
        '205' => '제국투기장 하드모드 클리어',
        '301' => '결투장 경험치 등급 상승',
        '401' => '아이템 강화',
        '402' => '아이템 증폭',
        '403' => '아이템 제련',
        '501' => '봉인된 자물쇠 아이템 획득',
        '502' => '퀘스트 레전더리 획득',
        '503' => '에컨 레전더리 획득',
        '504' => '에픽 아이템 획득(항아리)',
        '505' => '에픽 아이템 획득(지옥 파티)',
        '506' => '에픽 아이템 획득(조각 교환)',
        '507' => '에픽 아이템 획득(레이드)',
        '508' => '에픽 아이템 획득(상점)',
        '509' => '아이템 초월'
    ],

    // API에서 사용되는 컬럼 정보
    'columnInfo' => [
        'charactorId' => '캐릭터 고유 코드',
        'characterName' => '캐릭터 명',
        'jobId' => '캐릭터 직업 고유 코드',
        'jobName' => '캐릭터 직업 명칭',
        'jobGrowId' => '캐릭터 각성 직업 고유 코드',
        'jobGrowName' => '캐릭터 각성 직업 명칭',
        'itemId' => '아이템 고유 코드',
        'itemName' => '아이템명',
        'itemRarity' => '아이템 희귀도 등급',
        'itemType' => '아이템 타입',
        'itemTypeDetail' => '아이템 세부 타입',
        'itemAbility' => '아이템 고정 능력치',
        'itemAvailableLevel' => '아이템 장착 가능 레벨',
        'optionAbility' => '아이템 추가 or 선택 능력치',
        'refine' => '아이템 재련 수치',
        'reinforce' => '아이템 강화 수치',
        'setItemName' => '세트 아이템 명칭',
        'amplificationName' => '아이템 증폭 능력치 속성 ( 예 : 차원의 힘 )',
        'slotColor' => '아이템 슬롯 고유 색상',
        'slotNo' => '아이템 슬롯 고유 번호',
        'slotId' => '아이템 슬롯 고유 코드',
        'slotName' => '아이템 슬롯명',
        'description' => '부가 정보',
        'adventureName' => '모험단명',
        'guildId' => '길드 고유 코드',
        'guildName' => '길드명',
        'channelNo' => '채널 번호',
        'channelName' => '채널명',
        'dungeonName' => '던정명',
        'monsterName' => '몬스터명',
        'cloneAvatarName' => '클론 아바타 아이템명',
        'levelupCondition' => '스킬 레벨업 정보',
        'cooldownTime' => '스킬 쿨타임',
        'auctionNo' => '경매 고유 번호',
        'count' => '수량',
        'currentPrice' => '즉시 구매 가격',
        'unitPrice' => '즉시 구매 개당 가격',
        'price' => '현재 입찰 가격(즉시구매만 가능 상품의 경우 -1)',
        'averagePrice' => '아이템의 평균 구매 가격',
        'expireDate' => '마감 시간',
        'regDate' => '등록 시간',
        'beforeName' => '변경 전 캐릭터 명칭',
        'afterName' => '변경 후 캐릭터 명칭',
        'level' => '캐릭터 레벨',
        'raidName' => '레이드 명칭(안톤, 루크)',
        'phaseName' => '레이드, 마수던전 달성 단계',
        'single' => '싱글 레이드 여부',
        'point' => '마수던전 획득 포인트',
        'playTime' => '마수던전 참여 시간',
        'pvpGradeName' => '결투장 등급 명칭',
        'before' => '강화/증폭 전 상태',
        'after' => '강화/증폭/재련 성공 예정 상태',
        'result' => '강화/증폭/재련 성공 여부',
        'booster' => '봉인된 자물쇠 부스터 적용 유무',
        'hard' => '루크 레이드 하드 모드 여부',
        'requiredLevel' => '최소 스킬 제한 레벨',
        'itemStatus' => '장비 아이템 수치 정보',
        'itemObtainInfo' => '아이템 획득 정보',
        'itemExplain' => '아이템 부가 옵션에 대한 설명',
        'itemExplainDetail' => '아이템 부가 옵션에 대한 상세 설명',
        'itemFlavorText' => '아이템 배경담 - 스토리 설명',
        'itemReinforceSkill' => '장비 아이템 스킬 강화 정보',
        'cardInfo' => '카드 정보',
        'enchant' => '카드 업그레이드 수치 정보',
        'itemGradeName' => '아이템 등급명',
        'enchant' => '마법(보주) 부여'
    ]

];